"""Agrega columna nombre_servicio

Revision ID: 4b525cd73666
Revises: 9db60ea1fbc0
Create Date: 2025-09-21 16:33:41.905242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b525cd73666'
down_revision = '9db60ea1fbc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicios_adicionales', sa.Column('descripcion', sa.String(), nullable=False))
    op.alter_column('servicios_adicionales', 'nombre_servicio',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('servicios_adicionales', 'precio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servicios_adicionales', 'precio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('servicios_adicionales', 'nombre_servicio',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('servicios_adicionales', 'descripcion')
    # ### end Alembic commands ###

